// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwTfFAY3oMBStLLSRBchaTB1HcDZTZYsY',
    appId: '1:565585257990:web:1126b2ae9879e2cad34587',
    messagingSenderId: '565585257990',
    projectId: 'chat-app-de4f8',
    authDomain: 'chat-app-de4f8.firebaseapp.com',
    storageBucket: 'chat-app-de4f8.appspot.com',
    measurementId: 'G-0T5QCVVGB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfJXazPwjubQxQxymWpswNRjYW6-Yp9M',
    appId: '1:565585257990:android:045fb7b9732d9a77d34587',
    messagingSenderId: '565585257990',
    projectId: 'chat-app-de4f8',
    storageBucket: 'chat-app-de4f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9xzXSujx9QYqqusNpWF65X_yBrRdZ0s',
    appId: '1:565585257990:ios:3ae3c0d9b2c31872d34587',
    messagingSenderId: '565585257990',
    projectId: 'chat-app-de4f8',
    storageBucket: 'chat-app-de4f8.appspot.com',
    iosClientId: '565585257990-u3vqab5co65pn9kl3kbbf366sa11f3h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
